server:
  port: 8080

spring:
  application:
    name: commerce
  profiles:
    active: @profile.active@
  main:
    allow-circular-references: true
  servlet:
    multipart:
      # 单个文件最大限制
      max-file-size: 300MB
      # 多个文件最大限制
      max-request-size: 300MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: isDel
      logic-delete-value: 1
      logic-not-delete-value: 0

knife4j:
  enable: true
  setting:
    enable-version: true