spring:
  datasource:
    url: jdbc:mysql://${MYSQLCONNSTR_DB_URL}:3306/app_bank_qa?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=true&allowPublicKeyRetrieval=true
    username: ${MYSQLCONNSTR_DB_USERNAME}
    password: ${MYSQLCONNSTR_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100

common:
  login:
    enable: ${CUSTOMCONNSTR_COMMON_LOGIN_ENABLE:true}
  register:
    enable: ${CUSTOMCONNSTR_COMMON_REGISTER_ENABLE:true}

commerce:
  # jwt 秘钥
  jwt:
    pc: #pc端
      key: eXV4aXUtYm9zcwog
    app: #app端
      key: 5a6H5L+uYXBw56uv
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
